export enum ExplorerAction {
  Reset = 'explorer/reset',
  //ResetToken = "explorer/resetToken",
  VerifyToken = 'explorer/verifyToken',
  VerifyTokenSuccess = 'explorer/verifyTokenSuccess',
  VerifyTokenError = 'explorer/verifyTokenError',
  //Token = 'explorer/token',
  LoadRepositories = 'explorer/loadRepositories',
  LoadRepositoriesSuccess = 'explorer/loadRepositoriesSuccess',
  LoadRepositoriesError = 'explorer/loadRepositoriesError',
  LoadRepository = 'explorer/loadRepository',
  LoadRepositorySuccess = 'explorer/loadRepositorySuccess',
  LoadRepositoryError = 'explorer/loadRepositoryError',
  PageInfo = 'explorer/pageInfo',
}
